name: Build and Upload Debug Build to Firebase Distribution
on: push

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK to Firebase Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.0.0
        with:
          apk_path: app/build/outputs/apk/debug/app-debug.apk
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
